# -*- coding: utf-8 -*-
"""ADA10 Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BQTZK-96bRjVM7lQ-FLil_Cho-LuhGMq
"""

import multiprocessing
import time

def quick_sort(arr):
    """
    Perform quick sort on the input array.
    """
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quick_sort(left) + middle + quick_sort(right)

def parallel_quick_sort(arr):
    """
    Perform parallel quick sort on the input array.
    """
    if len(arr) <= 1:
        return arr

    # Split the array
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]

    # Create a pool of worker processes
    with multiprocessing.Pool() as pool:
        # Divide the tasks (sorting left and right subarrays) among the processes
        left_sorted, right_sorted = pool.map(quick_sort, [left, right])

    return left_sorted + middle + right_sorted

if __name__ == "__main__":
    import random

    # Generate a random array
    size = 100000 # Change this to a larger value for testing
    array = [random.randint(0, 1000) for _ in range(size)]
    print(f"Original array: {array}")

    # Perform both serial and parallel quick sorts

    serial_start = time.time()
    serial_sorted_array = quick_sort(array[:])
    serial_end = time.time()

    parallel_start = time.time()
    parallel_sorted_array = parallel_quick_sort(array[:])
    parallel_end = time.time()

    # print(f"Serial sorted array: {serial_sorted_array}")
    # print(f"Parallel sorted array: {parallel_sorted_array}")
    print(f"Time taken for serial quick sort: {serial_end - serial_start:.6f} seconds")
    print(f"Time taken for parallel quick sort: {parallel_end - parallel_start:.6f} seconds")